### PR TITLE
Fix for IE9 compatibility

### PR DESCRIPTION
**Pull request by mieszko4**

### CODE REVIEW

**Comment by romainberger** [comment]
Is the ternary an issue?

**Comment by mieszko4** [comment]
Not necessarily but it could be. Imagine situation in which `window.scrollY` is `0` not `undefined`. Then it will fallback to `window.pageYOffset` even though `window.scrollY` is supported possibly causing the next calculation of `top` to be `NaN`.
I am not sure if that would affect the actual implementation of `react-portal-tooltip`, in this way, however, it is explicit.

**Comment by romainberger** [comment]
You're right this could be an issue. Merged and available in v1.1.3

**Comment by mieszko4** [comment]
Great, thanx!

pon., 6.06.2016 o 17:14 użytkownik Romain Berger <notifications@github.com>
napisał:

**Pull request merged**
