### PR TITLE
refactor switch logic

### PR DESCRIPTION
**Pull request by petern-sc**
- Removed duplicate code
- Refactored switch logic in getStyle, to use object literals to simplify logic

@romainberger

### CODE REVIEW

**Comment by tanqhnguyen** [comment]
The convention here is to no have `;`, maybe we should follow that

**Comment by tanqhnguyen** [comment]
This PR removes duplicated code https://github.com/romainberger/react-portal-tooltip/pull/49

**Comment by romainberger** [comment]
Yeah I'd prefer to stay away from semicolons, they're added after transpilation anyway. Otherwise I like the objects literal 👍

**Comment by petern-sc** [comment]
Thanks for the comments! 

@tanqhnguyen 
Ah yes, I saw the other PR that removed the duplicate code. I wasn't sure if my changes would be overridden by that PR, so I repeated the removal of the duplicate here. I assumed that me removing it here, shouldn't change anything if the other PR goes through first?

I'm not too sure, this is my first PR, so let me know if I need to change anything. 

I've also removed the semicolons with the last commit 
@romainberger

**Comment by tanqhnguyen** [comment]
I am very confused, you refactored the old switch clause but then there is another (same old) switch case right below your new code (https://github.com/petern-sc/react-portal-tooltip/blob/d9c5f5d5e0a37676a30b06a9bf94db636c5621d7/src/index.js#L228), not sure what does it do?

**Comment by petern-sc** [comment]
@tanqhnguyen 
Yeah that was weird, I thought I had removed the duplicate code in the original commit.
The github differences view even show the lines being deleted. Perhaps when I ran a merge from upstream, it re-added the duplicate code. 

But I've updated the PR to remove them again, and they appear to be gone now.

**Comment by Redmega** [comment]
Interesting design pattern. Do they have to be functions though? What if they just returned the object and we did the mutation from the returned values instead?

**Comment by tanqhnguyen** [comment]
I might be drunk or something but I don't think your new code returns the same results as the old code does

For example, this case
```
case 'left':
  style.top = (top + parent.offsetHeight / 2) - ((this.state.height) / 2)
  style.left = left - this.state.width - this.margin

  if (arrow) {
    switch (arrow) {
      case 'top':
        style.top = (top + parent.offsetHeight / 2) - this.margin
        style.left = left - this.state.width - this.margin
        break

      case 'bottom':
        style.top = (top + parent.offsetHeight / 2) - this.state.height + this.margin
        style.left = left - this.state.width - this.margin
        break
    }
  }
  break
```

With your new code
```
executeFunctionIfExist(stylesFromPosition, arrow)
executeFunctionIfExist(stylesFromArrow, arrow)
```

I assume there is a typo in the first call and it should be position instead of arrow

And when position is `left` and arrow is `top`, your code call the following lines

```
style.top = top + parent.offsetHeight / 2 - this.state.height / 2
style.left = left - this.state.width - this.margin
style.top = top + parent.offsetHeight / 2 - this.margin
```

Old code calls the following lines
```
style.top = (top + parent.offsetHeight / 2) - ((this.state.height) / 2)
style.left = left - this.state.width - this.margin
style.top = (top + parent.offsetHeight / 2) - this.margin
style.left = left - this.state.width - this.margin
```

You have missed the last statement which can affect the final position

Also, this function should be put outside (as a standalone function) since we don't really need/want to create a new function everytime we call `getStyle`. Not that it will affect anything but just a best practice

```
const executeFunctionIfExist = (object, key) => {
  if (Object.prototype.hasOwnProperty.call(object, key)){
    object[key]()
  }
}
```

Can you double check the position calculation?

**Comment by petern-sc** [comment]
@tanqhnguyen 

style.left is being set to the same value twice in the original code, 
```javascript
style.left = left - this.state.width - this.margin
```
because none of the variables (left, state.width and margin) used in the calculations are being changed once they are set. 
_(On that note, they should probably be changed to const instead of let, but maybe for another PR?)_
There was a lot of duplicated logic in the original code which made it hard to understand what is going on, which is what led me to begin refactoring this in the first place. 
I've tested the results in an application that I was working on, and they still produce the same result. 

As for the custom function, I agree, I think that's a good idea. I've currently moved it to the end of the file, outside of the component. Do you think it'll be better there, or as a static function as part of the component?

@Redmega 
I'm not exactly sure I understand what you are describing. 
Are you saying, for example, stylesFromPosition should return a value for left and top, and then from there apply the values to the style object? 
e.g.
```javascript
const stylesFromPosition = {
      left: {
        top : top + parent.offsetHeight / 2 - this.state.height / 2,
        left : left - this.state.width - this.margin
      },
      ...
}
let styles = {...stylesFromPosition.left};

```

I think that could work, I went with this implementation because it felt simpler when I first started it, would be a smaller change to the codebase. But I'm happy to have a try at your method if other people prefer it. It can be used to refactor the code to a pure function rather than mutations as well.

**Comment by tanqhnguyen** [comment]
@petern-sc You are right, I must be drunk then :), everything is good 👍 let me know when you are ok with your PR (no more changes) and want it to be merged

**Comment by petern-sc** [comment]
@tanqhnguyen Yup, I'm happy with everything, thanks for the help in reviewing my first PR!

**Pull request merged**
