### PR TITLE
Update to react 0.14

### PR DESCRIPTION
**Pull request by romainberger**

### CODE REVIEW

**Comment by oyeanuj** [comment]
Hi @romainberger! Your component looks great and I was hoping to use it but am on React 0.14. What are your plans and timing for 0.14 compatibility?

Thanks!

**Comment by romainberger** [comment]
Hi! Check out the react-0.14 branch, it's ready!

**Comment by oyeanuj** [comment]
Great, thanks! I will check it out. Are you planning to merge it to master and upgrade the version of npm or waiting to add more changes?

**Comment by romainberger** [comment]
I've just published on npm the version 1.0.0 for React 0.14.

**Pull request merged**
